In [1]:
import pandas as pd
academic = pd.read_feather('./feather/academic.feather')#.to_csv('./tables/academics.csv',index=False)

# Tables concerning inproceedings (conference articles)
improceeding = pd.read_feather('./feather/improceeding_table.feather')#.to_csv('./tables/improceedings=.csv',index=False)
author_inproceeding = pd.read_feather('./feather/author_inproceedings.feather')#.to_csv('./tables/inproceedings_authors.csv',index=False)
booktitle_improceeding = pd.read_feather('./feather/improceeding_booktitle.feather')#.to_csv('./tables/improceedings_booktitles.csv',index=False)

# All tables concerning articles(journal articles)
article = pd.read_feather('./feather/articles_table.feather')#.to_csv('./tables/articles.csv',index=False)
author_article = pd.read_feather('./feather/author_article.feather')#.to_csv('./tables/article_authors.csv',index=False)
journal = pd.read_feather('./feather/journals_table.feather')#.to_csv('./tables/journals.csv',index=False)


# All tables concerning proceedings (conference proceedings => bundled conference articles)
editor_proceeding = pd.read_feather('./feather/editor_proceedings.feather')#.to_csv('./tables/proceedings_editors.csv',index=False)
publisher_proceeding = pd.read_feather('./feather/publisher_proceeding.feather')#.to_csv('./tables/proceedings_publishers.csv',index=False)
publisher = pd.read_feather('./feather/publisher_table.feather')#.to_csv('./tables/publishers.csv',index=False)
proceeding = pd.read_feather('./feather/proceeding_table.feather')#.to_csv('./tables/proceedings.csv',index=False)
booktitle_proceeding = pd.read_feather('./feather/proceeding_booktitle.feather')#.to_csv('./tables/proceedings_booktitles.csv',index=False)

# All tables concerning booktiles (conferences)
booktitle = pd.read_feather('./feather/booktitles_table.feather')#.to_csv('./tables/booktitles.csv',index=False)

In [2]:
article

,key,title,journal_id
0,conf/www/RamamohanaraoF07,Patterns Based Classifiers.,1936
1,conf/www/ZhaiL07,Extracting Web Data Using Instance-Based Learn...,1936
2,conf/www/NguKN07,Editorial.,1936
3,conf/www/Ericsson07,The Effects of XML Compression on SOAP Perform...,1936
4,conf/www/MartinBMMPSMSS07,Bringing Semantics to Web Services with OWL-S.,1936
...,...,...,...
2987941,tr/gte/TR-0244-12-93-165,MetaObject Protocol Concepts for a RISC Object...,545
2987942,tr/gte/TR-0146-06-91-165,Towards a Transaction Management System for DOM.,545
2987943,tr/gte/TR-0222-10-92-165,DARWIN: On the Incremental Migration of Legacy...,545
2987944,tr/dec/SRC1997-018,"The 1995 SQL Reunion: People, Project, and Pol...",395
2987945,tr/ucb/erl-m79-28,Muffin: A Distributed Database Machine,1909

In [3]:
#rename columns of tables
academic.columns = ['academic_id','academic_name']
article.columns = ['article_id','article_title','journal_id']
author_article.columns = ['academic_id','article_title']
journal.columns = ['journal_id','journal_name']
proceeding.columns = ['proceeding_id','proceeding_title','year','volume']
publisher.columns = ['publisher_id','publisher_name']
booktitle.columns = ['booktitle_id','booktitle_name']
booktitle_proceeding.columns = ['proceeding_id','booktitle_id']
improceeding.columns = ['improceeding_id','improceeding_title','pages','year']
booktitle_improceeding.columns = ['improceeding_id','booktitle_id']

In [39]:
import duckdb
querry1 = "Select * from publisher"
duckdb.query(querry1).to_df()

       publisher_id  publisher_name
0                -1             NaN
1                -1             NaN
2                -1             NaN
3                -1             NaN
4                -1             NaN
...             ...             ...
52233            -1             NaN
52234            -1             NaN
52235            -1             NaN
52236            -1             NaN
52237            -1             NaN

[52238 rows x 2 columns]

In [70]:
querry2 = "SELECT article.article_title, journal.journal_name FROM article INNER JOIN journal ON article.journal_id=journal.journal_id WHERE journal.journal_name='Theory Comput. Syst.' ORDER BY article.article_title"
duckdb.query(querry2).to_df()

                                          article_title          journal_name
0                     (Approximate) Uncertain Skylines.  Theory Comput. Syst.
1     (In)Existence of Equilibria for 2-Player, 2-Va...  Theory Comput. Syst.
2                  13/9 -Approximation for Graphic TSP.  Theory Comput. Syst.
3                        2-Stack Sorting is Polynomial.  Theory Comput. Syst.
4     2nd International Workshop on Complexity in Au...  Theory Comput. Syst.
...                                                 ...                   ...
1445                          Word-Mappings of Level 2.  Theory Comput. Syst.
1446       XML Compression via Directed Acyclic Graphs.  Theory Comput. Syst.
1447    XOR-Based Schemes for Fast Parallel IP Lookups.  Theory Comput. Syst.
1448  Zero-Dimensional Dynamical Systems, Formal Lan...  Theory Comput. Syst.
1449  Ã•(Congestion + Dilation) Hot-Potato Routing on...  Theory Comput. Syst.

[1450 rows x 2 columns]